[features]
seeds = false

[programs.devnet]
pda = "jmvZ2cau7tnjuUSum5ZvAa8dVpoy6B9g5dyNP7gcb2E"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/simeon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
